/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/models/importers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前固件支持的模型导入器及上传能力 */
        get: operations["getModelImporters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建持久化模型导入任务 */
        post: operations["createModelImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/imports/{importId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 全量上传 BModel 二进制文件
         * @description Content-Length 必须与创建任务时的 fileSize 完全相等。仅支持
         *     application/octet-stream。不得发送 Content-Range 或 Transfer-Encoding。
         *     浏览器会根据 Blob 自动产生 Content-Length，前端不得手动设置该受限请求头。
         *     失败重试必须重新发送整个文件，起始 offset 固定为 0。
         */
        put: operations["uploadModelImportContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/imports/{importId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询可恢复的导入任务 */
        get: operations["getModelImport"];
        put?: never;
        post?: never;
        /** 取消导入任务并删除临时文件 */
        delete: operations["cancelModelImport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/imports/{importId}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 校验并原子提交已上传模型
         * @description 校验 fileSize、BModel 魔数、导入器 metadata，并生成独立 factory.json。
         *     成功后 import ID 即 model ID，导入任务查询将返回 404。
         */
        post: operations["commitModelImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取已提交模型列表及存储空间 */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取模型完整元数据 */
        get: operations["getModel"];
        put?: never;
        post?: never;
        /**
         * 删除未被当前或待应用配置引用的模型
         * @description referenced 为 true 时必须先停用并等待配置任务成功。
         */
        delete: operations["deleteModel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{modelId}/deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取模型保存及实际应用的部署参数 */
        get: operations["getModelDeployment"];
        /**
         * 保存下次启用时使用的部署参数
         * @description 保存本身不会重启服务，也不会改变当前正在运行的参数。
         */
        put: operations["updateModelDeployment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{modelId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 启用可部署模型并创建配置任务
         * @description 空请求体时使用已保存 deployment 参数。也可提供一次性阈值和处理尺寸覆盖；覆盖值只用于
         *     本次启用，不修改已保存参数。检测模型启用时会关闭冲突的人脸、人体姿态和目标跟踪任务。
         */
        post: operations["activateModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{modelId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 停用模型并切回内置检测模型配置 */
        post: operations["deactivateModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询启用或停用配置任务
         * @description Manager 在内存中保留最近 16 个任务。任务不跨 Manager 进程重启持久化；收到 404 时
         *     前端应重新读取模型详情和部署状态，以 active、referenced 与 appliedParameters
         *     判断最终结果。
         */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 018f1234abcd5678 */
        ModelId: string;
        Error: {
            error: string;
        };
        UploadCapabilities: {
            /** @enum {string} */
            strategy: "single-request";
            /** @enum {string} */
            contentType: "application/octet-stream";
            /** @enum {boolean} */
            contentLengthRequired: true;
            /** @enum {string} */
            contentLengthSource: "body";
            /** @enum {boolean} */
            contentRange: false;
            /** @enum {boolean} */
            resumable: false;
            /** @enum {integer} */
            retryOffset: 0;
            /** @enum {string} */
            progressSource: "client";
        };
        ImporterCatalog: {
            upload: components["schemas"]["UploadCapabilities"];
            importers: components["schemas"]["ModelImporter"][];
            /**
             * Format: int64
             * @description 已扣除板端保留空间后，可用于新模型的字节数。
             */
            availableBytes: number;
        };
        ModelImporter: {
            /** @enum {string} */
            id: "detection.yolov5" | "detection.yolov6" | "detection.yolov7" | "detection.yolov8" | "detection.yolov10" | "detection.yolo26" | "detection.ppyoloe" | "detection.yolox" | "classification.image" | "pose.yolov8" | "segmentation.yolov8" | "feature.image" | "classification.sound_command";
            /** @enum {integer} */
            schemaVersion: 1;
            name: string;
            /** @enum {string} */
            task: "object_detection" | "image_classification" | "keypoint_detection" | "instance_segmentation" | "image_feature" | "sound_classification";
            enabled: boolean;
            deployable: boolean;
            /** @enum {integer} */
            maxFileSize: 16777216;
            /** @description 空数组表示当前固件只能保存该模型，尚无运行消费者。 */
            runtimeConsumers: "ipcamera.object_detection"[];
            /** @description JSON Schema 子集；前端以它决定该导入器的独立表单字段。 */
            metadataSchema: {
                [key: string]: unknown;
            };
            deploymentSchema?: {
                [key: string]: unknown;
            } | null;
            defaults?: {
                [key: string]: unknown;
            } | null;
            constraints?: {
                [key: string]: unknown;
            } | null;
        };
        Labels: string[];
        Vector3: number[];
        /** @enum {string} */
        RgbOrder: "RGB" | "BGR";
        AnchorPair: number[];
        AnchorGroup: components["schemas"]["AnchorPair"][];
        Anchors: components["schemas"]["AnchorGroup"][];
        DetectionMetadata: {
            labels: components["schemas"]["Labels"];
        };
        AnchoredDetectionMetadata: {
            labels: components["schemas"]["Labels"];
            anchors: components["schemas"]["Anchors"];
        };
        ImageClassificationMetadata: {
            labels: string[];
            rgbOrder: components["schemas"]["RgbOrder"];
            mean: components["schemas"]["Vector3"];
            /** @description 三项均不能为 0。 */
            std: components["schemas"]["Vector3"];
        };
        PoseMetadata: {
            labels: components["schemas"]["Labels"];
            keypoints: string[];
            rgbOrder: components["schemas"]["RgbOrder"];
            /** @description 索引必须小于 keypoints 数量，起点和终点不能相同。 */
            skeleton?: number[][];
        };
        SegmentationMetadata: {
            labels: components["schemas"]["Labels"];
            rgbOrder: components["schemas"]["RgbOrder"];
            /** @description 提供时长度必须与 labels 完全相同。 */
            colors?: string[];
        };
        ImageFeatureMetadata: {
            rgbOrder: components["schemas"]["RgbOrder"];
            mean: components["schemas"]["Vector3"];
            /** @description 三项均不能为 0。 */
            std: components["schemas"]["Vector3"];
        };
        SoundCommandMetadata: {
            labels: string[];
            /** @enum {integer} */
            sampleRate: 8000 | 16000;
            /** @enum {integer} */
            channels: 1;
            hopLength: number;
            /** @enum {string} */
            preprocessProfile: "common" | "fixed";
        };
        /** @description 实际结构必须与 importerId 对应导入器的 metadataSchema 完全一致。 */
        ImportMetadata: components["schemas"]["DetectionMetadata"] | components["schemas"]["AnchoredDetectionMetadata"] | components["schemas"]["ImageClassificationMetadata"] | components["schemas"]["PoseMetadata"] | components["schemas"]["SegmentationMetadata"] | components["schemas"]["ImageFeatureMetadata"] | components["schemas"]["SoundCommandMetadata"];
        CreateImportRequest: {
            /** @description 必须来自 GET /models/importers。 */
            importerId: string;
            /** @enum {integer} */
            schemaVersion: 1;
            name: string;
            fileSize: number;
            metadata: components["schemas"]["ImportMetadata"];
        };
        ImportTask: {
            id: components["schemas"]["ModelId"];
            /**
             * @description ready 不属于导入任务状态；commit 成功后应查询模型详情。
             * @enum {string}
             */
            status: "created" | "uploaded" | "failed";
            importerId: string;
            /** @enum {integer} */
            schemaVersion: 1;
            name: string;
            fileSize: number;
            /** @description 仅在上传完成或失败后持久化，不能作为续传 offset。 */
            uploadedBytes: number;
            /**
             * Format: int64
             * @description Unix 时间戳，单位秒。
             */
            createdAt: number;
            metadata: components["schemas"]["ImportMetadata"];
            checksum?: string;
            /** @description status 为 failed 时的上传错误，刷新后仍可读取。 */
            error?: string;
            /** @description 最近一次 commit 校验错误；状态仍为 uploaded，可以取消或重试 commit。 */
            validationError?: string;
        };
        DetectionDeploymentParameters: {
            /** @default 0.5 */
            threshold: number;
            processingSize: components["schemas"]["ProcessingSize"];
        };
        ProcessingSize: {
            /** @default 448 */
            width: number;
            /** @default 256 */
            height: number;
        };
        DeploymentState: {
            modelId: components["schemas"]["ModelId"];
            /** @enum {integer} */
            schemaVersion: 1;
            /** @enum {boolean} */
            deployable: true;
            active: boolean;
            referenced: boolean;
            parameters: components["schemas"]["DetectionDeploymentParameters"];
            appliedParameters: components["schemas"]["DetectionDeploymentParameters"] | null;
            parameterSchema: {
                [key: string]: unknown;
            };
        };
        ModelDetail: {
            id: components["schemas"]["ModelId"];
            /** @enum {string} */
            status: "ready";
            importerId: string;
            /** @enum {integer} */
            schemaVersion: 1;
            name: string;
            fileSize: number;
            uploadedBytes?: number;
            /** Format: int64 */
            createdAt: number;
            /** Format: int64 */
            committedAt: number;
            checksum?: string;
            metadata: components["schemas"]["ImportMetadata"];
            /** @enum {string} */
            modelType: "YOLOV5" | "YOLOV6" | "YOLOV7" | "YOLOV8" | "YOLOV10" | "YOLO26" | "PPYOLOE" | "YOLOX" | "CLS_IMG" | "KEYPOINT_YOLOV8POSE" | "YOLOV8_SEG" | "FEATURE_IMG" | "CLS_SOUND_COMMAND";
            task: string;
            deployable: boolean;
            deployment?: components["schemas"]["DetectionDeploymentParameters"] | null;
            /** @description 仅 GET 模型详情时返回；表示当前正在推理。 */
            active?: boolean;
            /** @description 仅 GET 模型详情时返回；表示运行配置仍引用该模型。 */
            referenced?: boolean;
        };
        ModelSummary: {
            id: components["schemas"]["ModelId"];
            /** @enum {string} */
            status: "ready";
            importerId: string;
            /** @enum {integer} */
            schemaVersion: 1;
            name: string;
            fileSize: number;
            /** Format: int64 */
            createdAt: number;
            /** Format: int64 */
            committedAt: number;
            modelType: string;
            task: string;
            deployable: boolean;
            metadataSummary: {
                labelsCount?: number;
                keypointsCount?: number;
            };
            active: boolean;
            referenced: boolean;
        };
        ModelStorage: {
            /** Format: int64 */
            totalBytes: number;
            /**
             * Format: int64
             * @description 文件系统原始可用字节数，尚未扣除 reservedBytes。
             */
            availableBytes: number;
            /**
             * Format: int64
             * @enum {integer}
             */
            reservedBytes: 2097152;
        };
        ModelList: {
            models: components["schemas"]["ModelSummary"][];
            storage: components["schemas"]["ModelStorage"];
        };
        AcceptedTask: {
            task_id: number;
            revision: string;
        };
        Task: {
            id: number;
            /** @enum {string} */
            state: "queued" | "running" | "succeeded" | "failed";
            /** @description 展示用阶段标识，不作为前端状态机枚举依据。 */
            stage: string;
            progress: number;
            message: string;
            rolled_back: boolean;
        };
    };
    responses: {
        /** @description 请求结构、字段、上传协议或模型校验无效 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 缺少 X-OVIS-CSRF 或 Origin 不允许 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 导入任务、模型或配置任务不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 模型不可部署、仍被引用或已有配置任务执行中 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 板端存储或响应生成失败 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        CsrfHeader: "1";
        ImportId: components["schemas"]["ModelId"];
        ModelId: components["schemas"]["ModelId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getModelImporters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 导入器目录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "upload": {
                     *         "strategy": "single-request",
                     *         "contentType": "application/octet-stream",
                     *         "contentLengthRequired": true,
                     *         "contentLengthSource": "body",
                     *         "contentRange": false,
                     *         "resumable": false,
                     *         "retryOffset": 0,
                     *         "progressSource": "client"
                     *       },
                     *       "importers": [
                     *         {
                     *           "id": "detection.yolov5",
                     *           "schemaVersion": 1,
                     *           "name": "YOLOv5 目标检测",
                     *           "task": "object_detection",
                     *           "enabled": true,
                     *           "deployable": true,
                     *           "maxFileSize": 16777216,
                     *           "runtimeConsumers": [
                     *             "ipcamera.object_detection"
                     *           ],
                     *           "metadataSchema": {
                     *             "type": "object",
                     *             "additionalProperties": false,
                     *             "required": [
                     *               "labels",
                     *               "anchors"
                     *             ],
                     *             "properties": {
                     *               "labels": {
                     *                 "type": "array",
                     *                 "minItems": 1,
                     *                 "maxItems": 256,
                     *                 "uniqueItems": true,
                     *                 "items": {
                     *                   "type": "string",
                     *                   "minLength": 1,
                     *                   "maxLength": 96
                     *                 }
                     *               },
                     *               "anchors": {
                     *                 "type": "array"
                     *               }
                     *             }
                     *           },
                     *           "deploymentSchema": {
                     *             "type": "object",
                     *             "additionalProperties": false,
                     *             "required": [
                     *               "threshold",
                     *               "processingSize"
                     *             ],
                     *             "properties": {
                     *               "threshold": {
                     *                 "type": "number",
                     *                 "minimum": 0,
                     *                 "maximum": 1,
                     *                 "default": 0.5,
                     *                 "step": 0.01
                     *               },
                     *               "processingSize": {
                     *                 "$ref": "#/components/schemas/ProcessingSize"
                     *               }
                     *             }
                     *           },
                     *           "defaults": {
                     *             "anchors": [
                     *               [
                     *                 [
                     *                   10,
                     *                   13
                     *                 ],
                     *                 [
                     *                   16,
                     *                   30
                     *                 ],
                     *                 [
                     *                   33,
                     *                   23
                     *                 ]
                     *               ],
                     *               [
                     *                 [
                     *                   30,
                     *                   61
                     *                 ],
                     *                 [
                     *                   62,
                     *                   45
                     *                 ],
                     *                 [
                     *                   59,
                     *                   119
                     *                 ]
                     *               ],
                     *               [
                     *                 [
                     *                   116,
                     *                   90
                     *                 ],
                     *                 [
                     *                   156,
                     *                   198
                     *                 ],
                     *                 [
                     *                   373,
                     *                   326
                     *                 ]
                     *               ]
                     *             ]
                     *           }
                     *         }
                     *       ],
                     *       "availableBytes": 52428800
                     *     }
                     */
                    "application/json": components["schemas"]["ImporterCatalog"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createModelImport: {
        parameters: {
            query?: never;
            header: {
                "X-OVIS-CSRF": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImportRequest"];
            };
        };
        responses: {
            /** @description 导入任务已创建；将 id 持久化后开始上传 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "018f1234abcd5678",
                     *       "status": "created",
                     *       "importerId": "detection.yolov8",
                     *       "schemaVersion": 1,
                     *       "name": "安全帽检测",
                     *       "fileSize": 3145728,
                     *       "uploadedBytes": 0,
                     *       "createdAt": 1784505600,
                     *       "metadata": {
                     *         "labels": [
                     *           "person",
                     *           "helmet"
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ImportTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    uploadModelImportContent: {
        parameters: {
            query?: never;
            header: {
                "X-OVIS-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                importId: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 完整文件已持久化 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "018f1234abcd5678",
                     *       "status": "uploaded",
                     *       "importerId": "detection.yolov8",
                     *       "schemaVersion": 1,
                     *       "name": "安全帽检测",
                     *       "fileSize": 3145728,
                     *       "uploadedBytes": 3145728,
                     *       "createdAt": 1784505600,
                     *       "checksum": "5f2d3a1017aa931c",
                     *       "metadata": {
                     *         "labels": [
                     *           "person",
                     *           "helmet"
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ImportTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getModelImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                importId: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 导入任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportTask"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelModelImport: {
        parameters: {
            query?: never;
            header: {
                "X-OVIS-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                importId: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    commitModelImport: {
        parameters: {
            query?: never;
            header: {
                "X-OVIS-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                importId: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型已进入 ready 状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: components["parameters"]["ModelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteModel: {
        parameters: {
            query?: never;
            header: {
                "X-OVIS-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                modelId: components["parameters"]["ModelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getModelDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: components["parameters"]["ModelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 部署参数 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "modelId": "018f1234abcd5678",
                     *       "schemaVersion": 1,
                     *       "deployable": true,
                     *       "active": true,
                     *       "referenced": true,
                     *       "parameters": {
                     *         "threshold": 0.55,
                     *         "processingSize": {
                     *           "width": 448,
                     *           "height": 256
                     *         }
                     *       },
                     *       "appliedParameters": {
                     *         "threshold": 0.55,
                     *         "processingSize": {
                     *           "width": 448,
                     *           "height": 256
                     *         }
                     *       },
                     *       "parameterSchema": {
                     *         "threshold": {
                     *           "type": "number",
                     *           "minimum": 0,
                     *           "maximum": 1,
                     *           "default": 0.5,
                     *           "step": 0.01
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["DeploymentState"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description 该模型类型当前不可部署 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateModelDeployment: {
        parameters: {
            query?: never;
            header: {
                "X-OVIS-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                modelId: components["parameters"]["ModelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "threshold": 0.55,
                 *       "processingSize": {
                 *         "width": 448,
                 *         "height": 256
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["DetectionDeploymentParameters"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentState"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    activateModel: {
        parameters: {
            query?: never;
            header: {
                "X-OVIS-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                modelId: components["parameters"]["ModelId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DetectionDeploymentParameters"];
            };
        };
        responses: {
            /** @description 配置任务已创建 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deactivateModel: {
        parameters: {
            query?: never;
            header: {
                "X-OVIS-CSRF": components["parameters"]["CsrfHeader"];
            };
            path: {
                modelId: components["parameters"]["ModelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 配置任务已创建 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedTask"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": 12,
                     *       "state": "running",
                     *       "stage": "restarting_ipcamera",
                     *       "progress": 60,
                     *       "message": "正在重启视频服务",
                     *       "rolled_back": false
                     *     }
                     */
                    "application/json": components["schemas"]["Task"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
